{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggquickeda
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggquickeda_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggquickeda/ggquickeda_{{ version }}.tar.gz
  sha256: ec9f234e5b8a2d2c44f635da0380e341394a34743c80d2ab6e2054135f513497

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dt
    - r-formula
    - r-ggally >=2.1.0
    - r-hmisc
    - r-rpostgres
    - r-colourpicker
    - r-dplyr
    - r-ggbeeswarm
    - r-ggplot2 >=3.3.2
    - r-ggpmisc
    - r-ggpubr
    - r-ggrepel >=0.7.0
    - r-ggstance
    - r-gridextra
    - r-markdown
    - r-plotly
    - r-quantreg
    - r-rlang
    - r-scales
    - r-shiny >=1.0.4
    - r-shinyfiles
    - r-shinyjqui
    - r-shinyjs >=1.1
    - r-stringr
    - r-survival
    - r-survminer
    - r-table1 >=1.2
    - r-tidyr
    - r-zoo
  run:
    - r-base
    - r-dt
    - r-formula
    - r-ggally >=2.1.0
    - r-hmisc
    - r-rpostgres
    - r-colourpicker
    - r-dplyr
    - r-ggbeeswarm
    - r-ggplot2 >=3.3.2
    - r-ggpmisc
    - r-ggpubr
    - r-ggrepel >=0.7.0
    - r-ggstance
    - r-gridextra
    - r-markdown
    - r-plotly
    - r-quantreg
    - r-rlang
    - r-scales
    - r-shiny >=1.0.4
    - r-shinyfiles
    - r-shinyjqui
    - r-shinyjs >=1.1
    - r-stringr
    - r-survival
    - r-survminer
    - r-table1 >=1.2
    - r-tidyr
    - r-zoo

test:
  commands:
    - $R -e "library('ggquickeda')"           # [not win]
    - "\"%R%\" -e \"library('ggquickeda')\""  # [win]

about:
  home: https://github.com/smouksassi/ggquickeda
  license: MIT
  summary: Quickly and easily perform exploratory data analysis by uploading your data as a 'csv' file. Start generating insights using 'ggplot2' plots and 'table1' tables with descriptive stats, all using an easy-to-use point and click 'Shiny' interface.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggquickeda
# Title: Quickly Explore Your Data Using 'ggplot2' and 'table1' Summary Tables
# Version: 0.1.6
# Authors@R: c( person("Samer", "Mouksassi", email = "samermouksassi@gmail.com", role = c("aut", "cre"),comment = c(ORCID = "https://orcid.org/0000-0002-7152-6654")), person("Dean", "Attali", email = "daattali@gmail.com", role = c("aut")), person("Benjamin", "Rich", email = "mail@benjaminrich.net", role = c("aut"), comment = "provided summary stats tables tab code"), person("Michael", "Sachs", email = "sachsmc@gmail.com", role = c("aut"), comment = "provided ggkm code") )
# Description: Quickly and easily perform exploratory data analysis by uploading your data as a 'csv' file. Start generating insights using 'ggplot2' plots and 'table1' tables with descriptive stats, all using an easy-to-use point and click 'Shiny' interface.
# URL: https://github.com/smouksassi/ggquickeda
# BugReports: https://github.com/smouksassi/ggquickeda/issues
# Depends: R (>= 3.5.0)
# Imports: colourpicker, dplyr, DT, Formula, GGally, ggplot2, ggpmisc, ggrepel (>= 0.7.0), ggstance, ggpubr, grDevices, grid, gridExtra, Hmisc, lazyeval, markdown, methods, plotly, quantreg, rlang, scales, shiny (>= 1.0.4), shinyjs (>= 1.1), shinyjqui, stats, stringr, survival, survminer, tidyr, table1 (>= 1.1), utils
# Suggests: knitr, rmarkdown
# License: MIT + file LICENSE
# SystemRequirements: pandoc with https support
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-04-17 13:38:02 UTC; smouksas
# Author: Samer Mouksassi [aut, cre] (<https://orcid.org/0000-0002-7152-6654>), Dean Attali [aut], Benjamin Rich [aut] (provided summary stats tables tab code), Michael Sachs [aut] (provided ggkm code)
# Maintainer: Samer Mouksassi <samermouksassi@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-04-17 14:00:03 UTC
